// <auto-generated />
using BotMyst.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BotMyst.Web.Migrations.ModuleOptions
{
    [DbContext(typeof(ModuleOptionsContext))]
    [Migration("20180724142012_Postgres")]
    partial class Postgres
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BotMyst.Bot.Options.Utility.LmgtfyOptions", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("ChannelBlacklist");

                    b.Property<string>("ChannelWhitelist");

                    b.Property<bool>("DeleteInvocationMessage");

                    b.Property<bool>("Dm");

                    b.Property<bool>("Enabled");

                    b.Property<string>("RoleBlacklist");

                    b.Property<string>("RoleWhitelist");

                    b.HasKey("GuildId");

                    b.ToTable("LmgtfyOptions");
                });

            modelBuilder.Entity("BotMyst.Bot.Options.Utility.UserInfoOptions", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("ChannelBlacklist");

                    b.Property<string>("ChannelWhitelist");

                    b.Property<bool>("DeleteInvocationMessage");

                    b.Property<bool>("Dm");

                    b.Property<bool>("Enabled");

                    b.Property<string>("RoleBlacklist");

                    b.Property<string>("RoleWhitelist");

                    b.HasKey("GuildId");

                    b.ToTable("UserInfoOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
