// <auto-generated />
using BotMyst.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace BotMyst.Web.Migrations
{
    [DbContext(typeof(ModulesContext))]
    [Migration("20180708132248_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("BotMyst.Web.Models.CommandDescriptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Command");

                    b.Property<string>("CommandOptionsType");

                    b.Property<int>("ModuleDescriptionId");

                    b.Property<string>("Name");

                    b.Property<string>("Summary");

                    b.HasKey("Id");

                    b.HasIndex("ModuleDescriptionId");

                    b.ToTable("CommandDescriptions");
                });

            modelBuilder.Entity("BotMyst.Web.Models.ModuleDescriptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("BotMyst.Web.Models.CommandDescriptionModel", b =>
                {
                    b.HasOne("BotMyst.Web.Models.ModuleDescriptionModel", "ModuleDescription")
                        .WithMany("CommandDescriptions")
                        .HasForeignKey("ModuleDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
