// <auto-generated />
using BotMyst.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace BotMyst.Web.Migrations
{
    [DbContext(typeof(ModulesContext))]
    [Migration("20180528133931_InitialCreate2")]
    partial class InitialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("BotMyst.Bot.Options.LmgtfyOptions", b =>
                {
                    b.Property<ulong>("Id");

                    b.Property<bool>("DeleteInvocationMessage");

                    b.Property<bool>("Dm");

                    b.Property<bool>("Enabled");

                    b.Property<string>("ExcludeChannels");

                    b.Property<string>("ExcludeRoles");

                    b.Property<string>("IncludeChannels");

                    b.Property<string>("IncludeRoles");

                    b.Property<bool>("InternetExplainer");

                    b.Property<string>("SearchEngine");

                    b.HasKey("Id");

                    b.ToTable("LmgtfyOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
